import { Link } from "react-router-dom";
import { ArrowRight, BookOpenCheck, Presentation, Radio, Users } from "lucide-react";

const paths = [{ title: "I want to learn", description: "Explore professional courses, join live classes, access resources and manage your learning in one place.", to: "/get-started/student", cta: "Start learning", icon: BookOpenCheck, points: ["Self-paced recorded courses", "Instructor-led live classes", "One learning dashboard"] }, { title: "I want to teach", description: "Create recorded courses or lead live classes with curriculum, resources, assignments and student management.", to: "/get-started/instructor", cta: "Start teaching", icon: Presentation, points: ["Publish professional courses", "Run scheduled live classes", "Grow your instructor profile"] }];
export default function GetStarted() { return <main className="min-h-[80vh] bg-[#f7f9f7] px-4 py-14 sm:px-6 lg:py-20"><div className="mx-auto max-w-6xl text-center"><p className="text-xs font-black uppercase tracking-[.15em] text-primary">Join QuranScholar</p><h1 className="mt-4 text-balance font-display text-[clamp(2.8rem,6vw,5rem)] font-black leading-none tracking-[-.05em]">How would you like to use QuranScholar?</h1><p className="mx-auto mt-5 max-w-2xl text-lg font-medium leading-8 text-muted-foreground">Choose your path now. You can still learn and teach from the same account later.</p><div className="mt-10 grid gap-6 text-left md:grid-cols-2">{paths.map(({ icon: Icon, ...path }) => <article key={path.title} className="flex flex-col rounded-3xl border border-border bg-white p-7 shadow-[0_16px_45px_rgba(18,48,40,.07)] sm:p-9"><span className="grid size-14 place-items-center rounded-2xl bg-primary text-white"><Icon className="size-6" /></span><h2 className="mt-7 font-display text-3xl font-black">{path.title}</h2><p className="mt-3 text-base font-medium leading-7 text-muted-foreground">{path.description}</p><ul className="mt-6 grid gap-3 text-sm font-bold">{path.points.map((point) => <li key={point} className="flex items-center gap-3"><span className="size-1.5 rounded-full bg-[#d6aa3a]" />{point}</li>)}</ul><Link to={path.to} className="mt-8 inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#0a3b35] px-5 text-sm font-black text-white no-underline">{path.cta}<ArrowRight className="size-4" /></Link></article>)}</div></div></main>; }

export function StudentStart() { return <JourneyPage eyebrow="For students" title="One place for every way you learn." intro="Move between focused self-paced study and live teacher-led learning without losing track of your progress." sections={[{ icon: BookOpenCheck, title: "Learn at your own pace", text: "Professional video courses with structured lessons, resources, assignments and progress tracking." }, { icon: Radio, title: "Learn with an instructor", text: "Scheduled live classes with direct guidance, class resources, attendance and a clear curriculum." }, { icon: Users, title: "Manage your learning", text: "See your next lesson, upcoming sessions, assignments and purchases in one dashboard." }]} action="Create student account" to="/register" />; }
export function InstructorStart() { return <JourneyPage eyebrow="For instructors" title="Teach your way on QuranScholar." intro="Build serious learning experiences—recorded, live, or both—using a workspace designed around teaching." sections={[{ icon: Presentation, title: "Create recorded courses", text: "Structure sections and lessons, upload video, provide resources and teach students at scale." }, { icon: Radio, title: "Teach live classes", text: "Set schedules, define tuition, share secure access and manage an ongoing learning community." }]} action="Become an instructor" to="/instructor/application" secondary={{ label: "Preview instructor workspace", to: "/instructor/dashboard" }} />; }

function JourneyPage({ eyebrow, title, intro, sections, action, to, secondary }) { return <main className="bg-[#f7f9f7]"><section className="bg-[#082f2b] px-4 py-16 text-white sm:px-6"><div className="mx-auto max-w-6xl"><p className="text-xs font-black uppercase tracking-[.15em] text-[#a6dace]">{eyebrow}</p><h1 className="mt-4 max-w-4xl font-display text-[clamp(2.8rem,6vw,5rem)] font-black leading-none tracking-[-.05em]">{title}</h1><p className="mt-6 max-w-2xl text-lg font-medium leading-8 text-white/65">{intro}</p></div></section><section className="mx-auto max-w-6xl px-4 py-14 sm:px-6"><div className={`grid gap-6 ${sections.length === 3 ? "lg:grid-cols-3" : "md:grid-cols-2"}`}>{sections.map(({ icon: Icon, title: heading, text }) => <article key={heading} className="rounded-2xl border border-border bg-white p-7"><span className="grid size-12 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5" /></span><h2 className="mt-6 font-display text-2xl font-black">{heading}</h2><p className="mt-3 text-sm font-medium leading-7 text-muted-foreground">{text}</p></article>)}</div><div className="mt-10 flex flex-wrap gap-3"><Link to={to} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-primary px-6 text-sm font-black text-white no-underline">{action}<ArrowRight className="size-4" /></Link>{secondary && <Link to={secondary.to} className="inline-flex min-h-12 items-center rounded-xl border border-border bg-white px-6 text-sm font-black text-foreground no-underline">{secondary.label}</Link>}</div></section></main>; }
