import { Link, useSearchParams } from "react-router-dom";
import { ArrowRight, CalendarDays, Clock3, Radio, Search, Users } from "lucide-react";
import { liveClasses } from "@/data/lmsData.js";
import { StatusBadge } from "@/components/lms/LmsComponents.jsx";

export const LiveClassCard = ({ item }) => <article className="group flex h-full flex-col overflow-hidden rounded-2xl border border-border bg-white shadow-[0_12px_35px_rgba(18,48,40,.06)] transition hover:-translate-y-1 hover:shadow-[0_18px_45px_rgba(18,48,40,.11)]"><div className="bg-[#0a3b35] p-5 text-white"><div className="flex items-center justify-between gap-3"><span className="inline-flex items-center gap-2 text-xs font-black uppercase tracking-[.12em] text-[#a8dace]"><Radio className="size-4" />Instructor-led</span><StatusBadge status={item.status} /></div><h2 className="mt-8 font-display text-2xl font-black leading-tight">{item.title}</h2><p className="mt-2 text-sm font-semibold text-white/60">with {item.instructor}</p></div><div className="flex flex-1 flex-col p-5"><p className="text-sm font-medium leading-6 text-muted-foreground">{item.shortDescription}</p><dl className="mt-5 grid gap-3 text-sm font-bold"><div className="flex items-center gap-2"><CalendarDays className="size-4 text-primary" />{item.schedule}</div><div className="flex items-center gap-2"><Clock3 className="size-4 text-primary" />{item.time} · {item.timezone}</div><div className="flex items-center gap-2"><Users className="size-4 text-primary" />{item.capacity - item.students} places available</div></dl><div className="mt-6 flex items-end justify-between gap-3 border-t border-border pt-5"><div><p className="text-xs font-bold text-muted-foreground">Admission SAR {item.admissionFee}</p><p className="font-display text-xl font-black">SAR {item.monthlyTuition}<span className="text-xs font-bold text-muted-foreground"> / month</span></p></div><Link to={`/live-classes/${item.slug}`} className="grid size-11 place-items-center rounded-xl bg-primary text-white no-underline transition group-hover:bg-primary-hover" aria-label={`View ${item.title}`}><ArrowRight className="size-5" /></Link></div></div></article>;

export default function LiveClasses() {
  const [params, setParams] = useSearchParams(); const query = params.get("search") || "";
  const filtered = liveClasses.filter((item) => `${item.title} ${item.category} ${item.instructor}`.toLowerCase().includes(query.toLowerCase()));
  return <main className="min-h-screen bg-[#f7f9f7] text-foreground"><section className="bg-[#082f2b] px-4 py-16 text-white sm:px-6 lg:py-20"><div className="mx-auto max-w-7xl"><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-black uppercase tracking-[.14em] text-[#b7e2d7]"><Radio className="size-4 text-[#f4c95d]" />Live learning</span><h1 className="mt-6 max-w-4xl text-balance font-display text-[clamp(2.8rem,6vw,5.2rem)] font-black leading-none tracking-[-.05em]">Learn live, with guidance that keeps you moving.</h1><p className="mt-6 max-w-2xl text-lg font-medium leading-8 text-white/68">Join scheduled online classes, follow a clear curriculum and receive direct support from trusted instructors.</p><div className="mt-8 max-w-xl rounded-xl border border-white/15 bg-white/10 p-2 backdrop-blur"><label className="flex items-center gap-3"><Search className="ml-2 size-5 text-white/55" /><span className="sr-only">Search live classes</span><input value={query} onChange={(event) => setParams(event.target.value ? { search: event.target.value } : {})} className="h-11 flex-1 bg-transparent text-sm font-semibold text-white outline-none placeholder:text-white/45" placeholder="Search topics or instructors" /></label></div></div></section><section className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.14em] text-primary">Available programs</p><h2 className="mt-2 font-display text-3xl font-black">Find your live class</h2></div><p className="text-sm font-bold text-muted-foreground">{filtered.length} classes · External meeting tools supported</p></div><div className="mt-8 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{filtered.map((item) => <LiveClassCard key={item.id} item={item} />)}</div></section></main>;
}
