import { NavLink, Outlet } from "react-router-dom";
import { BarChart3, BookOpen, ChevronLeft, CircleDollarSign, ClipboardCheck, LayoutDashboard, Library, Menu, MessageSquareText, Radio, Settings, UserRound, Users, X } from "lucide-react";
import { useState } from "react";
import { cn } from "@/lib/utils.js";

const studentLinks = [{ to: "/dashboard", label: "Overview", icon: LayoutDashboard, end: true }, { to: "/dashboard/learning", label: "My Learning", icon: BookOpen }, { to: "/dashboard/assignments", label: "Assignments", icon: ClipboardCheck }, { to: "/dashboard/wishlist", label: "Wishlist", icon: Library }, { to: "/dashboard/purchases", label: "Purchases", icon: CircleDollarSign }, { to: "/dashboard/profile", label: "Profile", icon: UserRound }, { to: "/dashboard/settings", label: "Settings", icon: Settings }];
const instructorLinks = [{ to: "/instructor/dashboard", label: "Overview", icon: LayoutDashboard }, { to: "/instructor/courses", label: "Courses", icon: BookOpen }, { to: "/instructor/live-classes", label: "Live Classes", icon: Radio }, { to: "/instructor/students", label: "Students", icon: Users }, { to: "/instructor/assignments", label: "Assignments", icon: ClipboardCheck }, { to: "/instructor/resources", label: "Resources", icon: Library }, { to: "/instructor/earnings", label: "Earnings", icon: CircleDollarSign }, { to: "/instructor/analytics", label: "Analytics", icon: BarChart3 }, { to: "/instructor/reviews", label: "Reviews", icon: MessageSquareText }, { to: "/instructor/profile", label: "Public Profile", icon: UserRound }, { to: "/instructor/settings", label: "Settings", icon: Settings }];

export default function WorkspaceLayout({ type = "student" }) { const [open, setOpen] = useState(false); const links = type === "instructor" ? instructorLinks : studentLinks; const title = type === "instructor" ? "Instructor workspace" : "Student dashboard"; const Sidebar = () => <div className="flex h-full flex-col bg-[#082f2b] text-white"><div className="flex min-h-18 items-center justify-between border-b border-white/10 px-5"><NavLink to="/" className="font-display text-xl font-black text-white no-underline">Quran<span className="text-[#f4c95d]">Scholar</span></NavLink><button onClick={() => setOpen(false)} className="grid size-9 place-items-center lg:hidden" aria-label="Close navigation"><X className="size-5" /></button></div><div className="px-5 py-5"><p className="text-[.68rem] font-black uppercase tracking-[.15em] text-white/40">{title}</p><p className="mt-2 text-sm font-bold">Assalamu alaikum, learner</p></div><nav className="min-h-0 flex-1 space-y-1 overflow-y-auto px-3 pb-5">{links.map(({ icon: Icon, ...link }) => <NavLink key={link.to} {...link} onClick={() => setOpen(false)} className={({ isActive }) => cn("flex min-h-11 items-center gap-3 rounded-lg px-3 text-sm font-bold text-white/62 no-underline transition hover:bg-white/8 hover:text-white", isActive && "bg-white/12 text-white")}><Icon className="size-[1.1rem]" />{link.label}</NavLink>)}</nav><NavLink to="/" className="m-3 flex min-h-11 items-center gap-2 rounded-lg border border-white/10 px-3 text-sm font-bold text-white/65 no-underline"><ChevronLeft className="size-4" />Back to website</NavLink></div>; return <div className="min-h-screen bg-[#f5f7f5] text-foreground lg:grid lg:grid-cols-[17rem_1fr]"><aside className="hidden h-screen lg:sticky lg:top-0 lg:block"><Sidebar /></aside>{open && <div className="fixed inset-0 z-50 bg-black/50 lg:hidden" onClick={(event) => event.target === event.currentTarget && setOpen(false)}><aside className="h-full w-[min(18rem,88vw)]"><Sidebar /></aside></div>}<div className="min-w-0"><header className="sticky top-0 z-30 flex min-h-16 items-center justify-between border-b border-border bg-white/90 px-4 backdrop-blur sm:px-6"><button onClick={() => setOpen(true)} className="grid size-10 place-items-center rounded-lg border border-border lg:hidden" aria-label="Open navigation"><Menu className="size-5" /></button><p className="hidden text-sm font-black sm:block">{title}</p><span className="grid size-9 place-items-center rounded-full bg-primary text-xs font-black text-white">MR</span></header><Outlet /></div></div>; }
